// svelte-todoapp/src/components/Task.svelte
<script>
  export let index;
  export let changeDone;
  export let task;

  // Todo
  let status = task.done ? "done" : "todo";
</script>

<input id={index} type="checkbox" on:change={() => changeDone(index)} />
<label class={status} for={index}>{task.text}</label>

<style>
  .done {
    text-decoration: line-through;
  }
</style>

// react-todoapp-lab1/src/components/Task.jsx
import React from "react";

export default function Task(props) {
  return (
    <>
      <input
        id={props.index}
        onChange={() => props.changeDone(props.index)}
        type="checkbox"
        defaultChecked={props.task.done}
      />
      <label htmlFor={props.index}>{props.task.text}</label>
    </>
  );
}
